### PR TITLE
fix "$where not allowed in this atlas tier"

### PR DESCRIPTION
**Pull request by WoozyDev**
when using .all() returns the error "MongoServerError: $where not allowed in this atlas tier"

### CODE REVIEW

**Review by archaeopteryx1 — CHANGES_REQUESTED** [review]
This update does not implement the logic that was inside `$where` condition. Please implement that.

**Comment by WoozyDev** [comment]
how do i check the atlast tier though

**Comment by realCartar** [comment]
These types of operators are restricted on Atlas' side for whatever reason they may have.
I can guarantee that you're running into this limitation as you are operating on Atlas' free-tier instance.
I believe any paid-tier instance has access to all MongoDB logic operators.

If you want to circumvent this, you can buy a *much* cheaper VPS (in comparison to an Atlas-hosted machine) and self-host an instance of MongoDB.

However, in relation to the actual commit you're trying to make; I don't believe this is constructive.

**Comment by Zorotic** [comment]
This has been closed for now as there is no way for us to control atlas. If this becomes a persistent issue amongst other users we will reopen the request to further investigate a possible workaround.

**Pull request closed without merging**
